### ISSUE TITLE
Installation not  WORKING

### ISSUE THREAD

**Issue by MrShadowDev** [DevEvil99/DevEvilBot-Discord-Bot#11]
![image](https://user-images.githubusercontent.com/71973368/198090787-f84d31e3-01fb-41a4-b25e-a7aa7a883a85.png)

The error shown up i already installed via npm i but it doesnt work. Can you fix it pls

**Comment by DevEvil99** [comment]
Delete better-sqlite3 from node_modules folder, and install it again
