### ISSUE TITLE
Used same events many times

### ISSUE THREAD

**Issue by Code-Williams** [DevEvil99/DevEvilBot-Discord-Bot#7]
اگه این بات برات مهمه کد هاش بهت پیشنهاد میکنم تمیز کاری بکنی فایل اصلی رو
خیلی از جاها میتونستی بجای چند بار استفاده کردن از دستورات شرطی، براشون لوپ بنویسی که بهتره
و کد هات رو زیاد پخش نوشتی که بهتره همشون توی یک ایونت مخصوص به خودشون باشن‌(اگه دقت کرده باشی هر تیکه از کدت که مثلا ایونت مسیج داره،‌توی ایونت جداگانه نوشته شده که این زیاد خوب نیست)

امیدوارم به دردت بخوره :) :rose:

**Comment by DevEvil99** [comment]
آره میدونم ولی من بعضی قسمت هارو خیلی وقت پیش که تازه کار بودم نوشتم و دیگه درستش نکردم ولی بزودی کد رو تمیز تر می‌نویسم چون باید آپدیت کنم به ورژن ۱۳ بعدا آپلود میکنم اینجا 
البته کمک هات تو اون اول راه یادم نمیره دمت گرم ❤

**Comment by Code-Williams** [comment]
:heart:
